// AUTO-GENERATED by scripts/generate-bible-data.mjs — do not hand-edit.
// Source: /Users/appdev/jerur/assets/data/bibles/key_english.js (old Jerur app), reshaped.
import type { BibleBook } from "../types";

export const BIBLE_BOOKS: BibleBook[] = [
  {
    "number": 1,
    "name": "Genesis",
    "chapterCount": 50,
    "testament": "OT",
    "group": 1
  },
  {
    "number": 2,
    "name": "Exodus",
    "chapterCount": 40,
    "testament": "OT",
    "group": 1
  },
  {
    "number": 3,
    "name": "Leviticus",
    "chapterCount": 27,
    "testament": "OT",
    "group": 1
  },
  {
    "number": 4,
    "name": "Numbers",
    "chapterCount": 36,
    "testament": "OT",
    "group": 1
  },
  {
    "number": 5,
    "name": "Deuteronomy",
    "chapterCount": 34,
    "testament": "OT",
    "group": 1
  },
  {
    "number": 6,
    "name": "Joshua",
    "chapterCount": 24,
    "testament": "OT",
    "group": 2
  },
  {
    "number": 7,
    "name": "Judges",
    "chapterCount": 21,
    "testament": "OT",
    "group": 2
  },
  {
    "number": 8,
    "name": "Ruth",
    "chapterCount": 4,
    "testament": "OT",
    "group": 2
  },
  {
    "number": 9,
    "name": "1 Samuel",
    "chapterCount": 31,
    "testament": "OT",
    "group": 2
  },
  {
    "number": 10,
    "name": "2 Samuel",
    "chapterCount": 24,
    "testament": "OT",
    "group": 2
  },
  {
    "number": 11,
    "name": "1 Kings",
    "chapterCount": 22,
    "testament": "OT",
    "group": 2
  },
  {
    "number": 12,
    "name": "2 Kings",
    "chapterCount": 25,
    "testament": "OT",
    "group": 2
  },
  {
    "number": 13,
    "name": "1 Chronicles",
    "chapterCount": 29,
    "testament": "OT",
    "group": 2
  },
  {
    "number": 14,
    "name": "2 Chronicles",
    "chapterCount": 36,
    "testament": "OT",
    "group": 2
  },
  {
    "number": 15,
    "name": "Ezra",
    "chapterCount": 10,
    "testament": "OT",
    "group": 2
  },
  {
    "number": 16,
    "name": "Nehemiah",
    "chapterCount": 13,
    "testament": "OT",
    "group": 2
  },
  {
    "number": 17,
    "name": "Esther",
    "chapterCount": 10,
    "testament": "OT",
    "group": 2
  },
  {
    "number": 18,
    "name": "Job",
    "chapterCount": 42,
    "testament": "OT",
    "group": 3
  },
  {
    "number": 19,
    "name": "Psalms",
    "chapterCount": 150,
    "testament": "OT",
    "group": 3
  },
  {
    "number": 20,
    "name": "Proverbs",
    "chapterCount": 31,
    "testament": "OT",
    "group": 3
  },
  {
    "number": 21,
    "name": "Ecclesiastes",
    "chapterCount": 12,
    "testament": "OT",
    "group": 3
  },
  {
    "number": 22,
    "name": "Song of Solomon",
    "chapterCount": 8,
    "testament": "OT",
    "group": 3
  },
  {
    "number": 23,
    "name": "Isaiah",
    "chapterCount": 66,
    "testament": "OT",
    "group": 4
  },
  {
    "number": 24,
    "name": "Jeremiah",
    "chapterCount": 52,
    "testament": "OT",
    "group": 4
  },
  {
    "number": 25,
    "name": "Lamentations",
    "chapterCount": 5,
    "testament": "OT",
    "group": 4
  },
  {
    "number": 26,
    "name": "Ezekiel",
    "chapterCount": 48,
    "testament": "OT",
    "group": 4
  },
  {
    "number": 27,
    "name": "Daniel",
    "chapterCount": 12,
    "testament": "OT",
    "group": 4
  },
  {
    "number": 28,
    "name": "Hosea",
    "chapterCount": 14,
    "testament": "OT",
    "group": 4
  },
  {
    "number": 29,
    "name": "Joel",
    "chapterCount": 3,
    "testament": "OT",
    "group": 4
  },
  {
    "number": 30,
    "name": "Amos",
    "chapterCount": 9,
    "testament": "OT",
    "group": 4
  },
  {
    "number": 31,
    "name": "Obadiah",
    "chapterCount": 1,
    "testament": "OT",
    "group": 4
  },
  {
    "number": 32,
    "name": "Jonah",
    "chapterCount": 4,
    "testament": "OT",
    "group": 4
  },
  {
    "number": 33,
    "name": "Micah",
    "chapterCount": 7,
    "testament": "OT",
    "group": 4
  },
  {
    "number": 34,
    "name": "Nahum",
    "chapterCount": 3,
    "testament": "OT",
    "group": 4
  },
  {
    "number": 35,
    "name": "Habakkuk",
    "chapterCount": 3,
    "testament": "OT",
    "group": 4
  },
  {
    "number": 36,
    "name": "Zephaniah",
    "chapterCount": 3,
    "testament": "OT",
    "group": 4
  },
  {
    "number": 37,
    "name": "Haggai",
    "chapterCount": 2,
    "testament": "OT",
    "group": 4
  },
  {
    "number": 38,
    "name": "Zechariah",
    "chapterCount": 14,
    "testament": "OT",
    "group": 4
  },
  {
    "number": 39,
    "name": "Malachi",
    "chapterCount": 4,
    "testament": "OT",
    "group": 4
  },
  {
    "number": 40,
    "name": "Matthew",
    "chapterCount": 28,
    "testament": "NT",
    "group": 5
  },
  {
    "number": 41,
    "name": "Mark",
    "chapterCount": 16,
    "testament": "NT",
    "group": 5
  },
  {
    "number": 42,
    "name": "Luke",
    "chapterCount": 24,
    "testament": "NT",
    "group": 5
  },
  {
    "number": 43,
    "name": "John",
    "chapterCount": 21,
    "testament": "NT",
    "group": 5
  },
  {
    "number": 44,
    "name": "Acts",
    "chapterCount": 28,
    "testament": "NT",
    "group": 6
  },
  {
    "number": 45,
    "name": "Romans",
    "chapterCount": 16,
    "testament": "NT",
    "group": 7
  },
  {
    "number": 46,
    "name": "1 Corinthians",
    "chapterCount": 16,
    "testament": "NT",
    "group": 7
  },
  {
    "number": 47,
    "name": "2 Corinthians",
    "chapterCount": 13,
    "testament": "NT",
    "group": 7
  },
  {
    "number": 48,
    "name": "Galatians",
    "chapterCount": 6,
    "testament": "NT",
    "group": 7
  },
  {
    "number": 49,
    "name": "Ephesians",
    "chapterCount": 6,
    "testament": "NT",
    "group": 7
  },
  {
    "number": 50,
    "name": "Philippians",
    "chapterCount": 4,
    "testament": "NT",
    "group": 7
  },
  {
    "number": 51,
    "name": "Colossians",
    "chapterCount": 4,
    "testament": "NT",
    "group": 7
  },
  {
    "number": 52,
    "name": "1 Thessalonians",
    "chapterCount": 5,
    "testament": "NT",
    "group": 7
  },
  {
    "number": 53,
    "name": "2 Thessalonians",
    "chapterCount": 3,
    "testament": "NT",
    "group": 7
  },
  {
    "number": 54,
    "name": "1 Timothy",
    "chapterCount": 6,
    "testament": "NT",
    "group": 7
  },
  {
    "number": 55,
    "name": "2 Timothy",
    "chapterCount": 4,
    "testament": "NT",
    "group": 7
  },
  {
    "number": 56,
    "name": "Titus",
    "chapterCount": 3,
    "testament": "NT",
    "group": 7
  },
  {
    "number": 57,
    "name": "Philemon",
    "chapterCount": 1,
    "testament": "NT",
    "group": 7
  },
  {
    "number": 58,
    "name": "Hebrews",
    "chapterCount": 13,
    "testament": "NT",
    "group": 7
  },
  {
    "number": 59,
    "name": "James",
    "chapterCount": 5,
    "testament": "NT",
    "group": 7
  },
  {
    "number": 60,
    "name": "1 Peter",
    "chapterCount": 5,
    "testament": "NT",
    "group": 7
  },
  {
    "number": 61,
    "name": "2 Peter",
    "chapterCount": 3,
    "testament": "NT",
    "group": 7
  },
  {
    "number": 62,
    "name": "1 John",
    "chapterCount": 5,
    "testament": "NT",
    "group": 7
  },
  {
    "number": 63,
    "name": "2 John",
    "chapterCount": 1,
    "testament": "NT",
    "group": 7
  },
  {
    "number": 64,
    "name": "3 John",
    "chapterCount": 1,
    "testament": "NT",
    "group": 7
  },
  {
    "number": 65,
    "name": "Jude",
    "chapterCount": 1,
    "testament": "NT",
    "group": 7
  },
  {
    "number": 66,
    "name": "Revelation",
    "chapterCount": 22,
    "testament": "NT",
    "group": 8
  }
];
