import { Image, TextInput, type ImageSourcePropType } from "react-native";
import type { ReactNode } from "react";
import Svg, { Circle, Defs, LinearGradient as SvgLinearGradient, Rect, Stop } from "react-native-svg";
import { SvgUri } from "react-native-svg";
import { Feather } from "@expo/vector-icons";
import { Stack, StyledButton, StyledPressable } from "fluent-styles";
import { Text } from "./text";
import { COLORS } from "../theme/colors";
import { SHADOW_CARD, SHADOW_SOFT } from "../theme/shadows";
import { COLLECTION_COVER_ARTWORK, STORY_ARTWORK } from "../bible-discovery/assets";
import type { DiscoveryCollection, DiscoveryStory } from "../bible-discovery/types";

export function DiscoveryArtwork({ source, height = 180, aspectRatio }: { source: ImageSourcePropType; height?: number; aspectRatio?: number }) {
  const uri = Image.resolveAssetSource(source)?.uri;
  const isSvg = uri?.split("?")[0].endsWith(".svg");
  return <Stack height={aspectRatio ? undefined : height} aspectRatio={aspectRatio} overflow="hidden" backgroundColor={COLORS.paperAlt}>{uri ? isSvg ? <SvgUri uri={uri} width="100%" height="100%" /> : <Image source={source} resizeMode="cover" style={{ width: "100%", height: "100%" }} /> : null}</Stack>;
}

export function DiscoveryProgressRing({ percent, size = 54 }: { percent: number; size?: number }) {
  const stroke = 5; const radius = (size - stroke) / 2; const circumference = 2 * Math.PI * radius;
  return <Stack width={size} height={size} alignItems="center" justifyContent="center"><Svg width={size} height={size} style={{ position: "absolute", transform: [{ rotate: "-90deg" }] }}><Circle cx={size / 2} cy={size / 2} r={radius} stroke={COLORS.paperAlt} strokeWidth={stroke} fill="none" /><Circle cx={size / 2} cy={size / 2} r={radius} stroke={COLORS.indigo} strokeWidth={stroke} fill="none" strokeLinecap="round" strokeDasharray={`${circumference} ${circumference}`} strokeDashoffset={circumference * (1 - percent / 100)} /></Svg><Text fontSize={size < 50 ? 10 : 11} fontWeight="800" color={COLORS.ink}>{percent}%</Text></Stack>;
}

export function DiscoveryFontSizeButton({ onPress }: { onPress: () => void }) {
  return <StyledButton icon compact backgroundColor={COLORS.goldPale} onPress={onPress} accessibilityLabel="Change text size"><Feather name="type" size={18} color={COLORS.goldDeep} /></StyledButton>;
}

export function DiscoveryCollectionCard({ collection, storyCount, onPress, width = 220, height = 272, fontScale = 1 }: { collection: DiscoveryCollection; storyCount: number; onPress: () => void; width?: number | `${number}%`; height?: number; fontScale?: number }) {
  return <StyledPressable accessibilityRole="button" accessibilityLabel={`Open ${collection.title}, ${storyCount} stories`} onPress={onPress} style={{ width }}><Stack width="100%" height={height} overflow="hidden" borderRadius={22} backgroundColor={COLORS.paperAlt} borderWidth={1} borderColor={COLORS.border} style={SHADOW_CARD}><Stack style={{ position: "absolute", inset: 0 }}><DiscoveryArtwork source={COLLECTION_COVER_ARTWORK[collection.id]} height={height} /></Stack><Stack height="62%" style={{ position: "absolute", left: 0, right: 0, bottom: 0 }}><Svg width="100%" height="100%"><Defs><SvgLinearGradient id={`collection-fade-${collection.id}`} x1="0" y1="0" x2="0" y2="1"><Stop offset="0" stopColor="#000000" stopOpacity="0" /><Stop offset="0.42" stopColor="#000000" stopOpacity="0.48" /><Stop offset="1" stopColor="#000000" stopOpacity="0.9" /></SvgLinearGradient></Defs><Rect width="100%" height="100%" fill={`url(#collection-fade-${collection.id})`} /></Svg></Stack><Stack padding={15} gap={5} style={{ position: "absolute", left: 0, right: 0, bottom: 0 }}><Stack alignSelf="flex-start" paddingHorizontal={9} minHeight={23} justifyContent="center" borderRadius={12} backgroundColor={COLORS.sage}><Text fontSize={9 * fontScale} fontWeight="800" letterSpacing={0.8} color={COLORS.onPrimary}>COLLECTION</Text></Stack><Text numberOfLines={1} fontSize={18 * fontScale} fontWeight="800" color="#FFFFFF">{collection.title}</Text><Text numberOfLines={2} fontSize={11.5 * fontScale} color="rgba(255,255,255,0.82)" style={{ lineHeight: 16 * fontScale }}>{collection.description}</Text><Stack horizontal alignItems="center" justifyContent="space-between" marginTop={2}><Text fontSize={11.5 * fontScale} fontWeight="700" color="rgba(255,255,255,0.9)">{storyCount} {storyCount === 1 ? "story" : "stories"}</Text><Stack width={34} height={34} borderRadius={17} alignItems="center" justifyContent="center" backgroundColor="rgba(255,255,255,0.18)" borderWidth={1} borderColor="rgba(255,255,255,0.25)"><Feather name="arrow-up-right" size={17} color="#FFFFFF" /></Stack></Stack></Stack></Stack></StyledPressable>;
}

export function DiscoveryStoryCard({ story, percent, onPress, compact = false, collectionLayout = false, fontScale = 1 }: { story: DiscoveryStory; percent: number; onPress: () => void; compact?: boolean; collectionLayout?: boolean; fontScale?: number }) {
  return <StyledPressable accessibilityRole="button" accessibilityLabel={`Open ${story.title}`} onPress={onPress} style={{ width: "100%" }}><Stack width="100%" overflow="hidden" borderRadius={20} backgroundColor={COLORS.white} borderWidth={1} borderColor={COLORS.chromeBorder} style={SHADOW_SOFT}>{collectionLayout ? <><DiscoveryArtwork source={STORY_ARTWORK[story.id]} aspectRatio={16 / 9} /><Stack minHeight={132 * fontScale} paddingHorizontal={15} paddingVertical={12} gap={4} justifyContent="center"><Text numberOfLines={1} fontSize={16 * fontScale} fontWeight="800" color={COLORS.ink}>{story.title}</Text><Text numberOfLines={1} fontSize={12 * fontScale} color={COLORS.inkSoft}>{story.subtitle}</Text><Text numberOfLines={2} ellipsizeMode="tail" fontSize={11.5 * fontScale} color={COLORS.inkSoftest} style={{ lineHeight: 16 * fontScale }}>{story.description}</Text><Text numberOfLines={1} fontSize={11 * fontScale} color={COLORS.inkSoftest}>{story.estimatedMinutes} min · {story.flashcards.length} cards</Text><ProgressBar percent={percent} /></Stack></> : compact ? <Stack horizontal><Stack width={126}><DiscoveryArtwork source={STORY_ARTWORK[story.id]} height={128} /></Stack><Stack flex={1} padding={15} gap={5} justifyContent="center"><Text numberOfLines={1} fontSize={16} fontWeight="800" color={COLORS.ink}>{story.title}</Text><Text numberOfLines={1} fontSize={12} color={COLORS.inkSoft}>{story.subtitle}</Text><Text fontSize={11} color={COLORS.inkSoftest}>{story.estimatedMinutes} min · {story.flashcards.length} cards</Text><ProgressBar percent={percent} /></Stack></Stack> : <><DiscoveryArtwork source={STORY_ARTWORK[story.id]} height={150} /><Stack padding={15} gap={5}><Text fontSize={17} fontWeight="800" color={COLORS.ink}>{story.title}</Text><Text numberOfLines={1} fontSize={12.5} color={COLORS.inkSoft}>{story.subtitle}</Text><Stack horizontal justifyContent="space-between" alignItems="center"><Text fontSize={11} color={COLORS.inkSoftest}>{story.estimatedMinutes} min</Text>{percent === 100 ? <Feather name="check-circle" size={17} color={COLORS.sage} /> : <Text fontSize={11} fontWeight="700" color={COLORS.indigo}>{percent}%</Text>}</Stack><ProgressBar percent={percent} /></Stack></>}</Stack></StyledPressable>;
}

export function ProgressBar({ percent }: { percent: number }) { return <Stack height={6} borderRadius={3} overflow="hidden" backgroundColor={COLORS.paperAlt}><Stack width={`${percent}%`} height={6} borderRadius={3} backgroundColor={COLORS.indigo} /></Stack>; }

export function DiscoverySearch({ value, onChangeText }: { value: string; onChangeText: (value: string) => void }) {
  return <Stack horizontal alignItems="center" minHeight={50} paddingHorizontal={15} borderRadius={16} backgroundColor={COLORS.paperAlt} borderWidth={1} borderColor={COLORS.chromeBorder}><Feather name="search" size={18} color={COLORS.inkSoft} /><TextInput accessibilityLabel="Search Bible Discovery stories" value={value} onChangeText={onChangeText} placeholder="Search stories" placeholderTextColor={COLORS.inkSoftest} style={{ flex: 1, minHeight: 48, paddingHorizontal: 11, color: COLORS.ink, fontSize: 14 }} /></Stack>;
}

export function DiscoveryEmpty({ title = "Nothing found", message = "Try changing your search or filter." }: { title?: string; message?: string }) { return <Stack alignItems="center" padding={40} gap={7}><Feather name="book-open" size={28} color={COLORS.inkSoftest} /><Text fontSize={16} fontWeight="800" color={COLORS.ink}>{title}</Text><Text textAlign="center" fontSize={13} color={COLORS.inkSoft}>{message}</Text></Stack>; }

export function EditorialCard({ icon, title, children }: { icon: string; title: string; children: ReactNode }) { return <Stack padding={19} gap={11} borderRadius={20} backgroundColor={COLORS.white} borderWidth={1} borderColor={COLORS.chromeBorder} style={SHADOW_CARD}><Stack horizontal alignItems="center" gap={9}><Stack width={36} height={36} borderRadius={18} alignItems="center" justifyContent="center" backgroundColor={COLORS.goldPale}><Feather name={icon as never} size={17} color={COLORS.goldDeep} /></Stack><Text fontSize={17} fontWeight="800" color={COLORS.ink}>{title}</Text></Stack>{children}</Stack>; }
